version: 0.2

env:
  variables:
    S3_BUCKET_NAME: career-adivce-partner
    EC2_INSTANCE_ID: i-08a40d8c2c9193d3b
    REGION: ap-south-2
    APP_DIR: /opt/cap/frontend

phases:
  install:
    commands:
      - echo "Installing Node.js 18 and npm..."
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get update -y
      - apt-get install -y nodejs zip unzip
      - node -v
      - npm -v

  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building Next.js app..."
      - npm run build # this runs next build
      - |
        # Export as a static site. Ensure package.json has: "export": "next export"
        if npm run | grep -q "export"; then
          echo "Running next export..."
          npm run export       # produces out/ directory
        else
          echo "No \"export\" script found in package.json. Creating static export using next export anyway."
          npx next export
        fi
      - echo "Build output (out/):"
      - ls -lah out || true

  post_build:
    commands:
      - echo "Preparing build.zip..."
      - rm -f /tmp/build.zip || true
      - cd out
      - zip -r /tmp/build.zip . # zip the exported static site
      - cd -
      - echo "Uploading build.zip to s3://$S3_BUCKET_NAME/build.zip"
      - aws s3 cp /tmp/build.zip s3://"$S3_BUCKET_NAME"/build.zip --region "$REGION"
      - echo "Sending SSM command to EC2 to deploy the static files..."
      - |
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids "$EC2_INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Next.js static export" \
          --parameters commands='[
            "set -e",
            "echo Cleaning app directory...",
            "rm -rf '"$APP_DIR"'/* || true",
            "echo Preparing temp directory...",
            "rm -rf /tmp/build || true",
            "mkdir -p /tmp/build",
            "cd /tmp/build",
            "echo Downloading build.zip from S3...",
            "aws s3 cp s3://'"$S3_BUCKET_NAME"'/build.zip ./build.zip --region '"$REGION"'",
            "unzip -o build.zip",
            "cp -r ./* '"$APP_DIR"'/",
            "rm -rf /tmp/build",
            "echo Deployment completed."
          ]' \
          --region "$REGION" \
          --query "Command.CommandId" \
          --output text)
        echo "SSM Command ID: $COMMAND_ID"
        echo "Waiting for SSM command to complete..."
        aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID" \
            --region "$REGION"
        echo "Fetching SSM command standard output:"
        aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID" \
            --region "$REGION" \
            --query "StandardOutputContent" \
            --output text
        echo "Fetching SSM command error output:"
        aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID" \
            --region "$REGION" \
            --query "StandardErrorContent" \
            --output text

artifacts:
  files:
    - out/**/*
